CUDNN_BENCHMARK: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  SAMPLE_PER_CLASS: -1
  SAMPLE_SEED: 0
  TEST:
  - coco_2way_cls40_41
  - coco_2way_cls40_42
  - coco_2way_cls40_43
  - coco_2way_cls40_44
  - coco_2way_cls40_45
  - coco_2way_cls40_46
  - coco_2way_cls40_47
  - coco_2way_cls40_48
  - coco_2way_cls40_49
  - coco_2way_cls40_50
  - coco_2way_cls40_51
  - coco_2way_cls40_52
  - coco_2way_cls40_53
  - coco_2way_cls40_54
  - coco_2way_cls40_55
  - coco_2way_cls40_56
  - coco_2way_cls40_57
  - coco_2way_cls40_58
  - coco_2way_cls40_59
  - coco_2way_cls41_42
  - coco_2way_cls41_43
  - coco_2way_cls41_44
  - coco_2way_cls41_45
  - coco_2way_cls41_46
  - coco_2way_cls41_47
  - coco_2way_cls41_48
  - coco_2way_cls41_49
  - coco_2way_cls41_50
  - coco_2way_cls41_51
  - coco_2way_cls41_52
  - coco_2way_cls41_53
  - coco_2way_cls41_54
  - coco_2way_cls41_55
  - coco_2way_cls41_56
  - coco_2way_cls41_57
  - coco_2way_cls41_58
  - coco_2way_cls41_59
  - coco_2way_cls42_43
  - coco_2way_cls42_44
  - coco_2way_cls42_45
  - coco_2way_cls42_46
  - coco_2way_cls42_47
  - coco_2way_cls42_48
  - coco_2way_cls42_49
  - coco_2way_cls42_50
  - coco_2way_cls42_51
  - coco_2way_cls42_52
  - coco_2way_cls42_53
  - coco_2way_cls42_54
  - coco_2way_cls42_55
  - coco_2way_cls42_56
  - coco_2way_cls42_58
  - coco_2way_cls43_44
  - coco_2way_cls43_45
  - coco_2way_cls43_46
  - coco_2way_cls43_47
  - coco_2way_cls43_48
  - coco_2way_cls43_49
  - coco_2way_cls43_50
  - coco_2way_cls43_51
  - coco_2way_cls43_52
  - coco_2way_cls43_53
  - coco_2way_cls43_54
  - coco_2way_cls43_55
  - coco_2way_cls43_56
  - coco_2way_cls43_57
  - coco_2way_cls43_58
  - coco_2way_cls43_59
  - coco_2way_cls44_45
  - coco_2way_cls44_46
  - coco_2way_cls44_47
  - coco_2way_cls44_48
  - coco_2way_cls44_49
  - coco_2way_cls44_50
  - coco_2way_cls44_51
  - coco_2way_cls44_52
  - coco_2way_cls44_53
  - coco_2way_cls44_54
  - coco_2way_cls44_55
  - coco_2way_cls44_56
  - coco_2way_cls44_58
  - coco_2way_cls45_46
  - coco_2way_cls45_47
  - coco_2way_cls45_48
  - coco_2way_cls45_49
  - coco_2way_cls45_50
  - coco_2way_cls45_51
  - coco_2way_cls45_52
  - coco_2way_cls45_53
  - coco_2way_cls45_54
  - coco_2way_cls45_55
  - coco_2way_cls45_56
  - coco_2way_cls45_57
  - coco_2way_cls45_58
  - coco_2way_cls45_59
  - coco_2way_cls46_47
  - coco_2way_cls46_48
  - coco_2way_cls46_49
  - coco_2way_cls46_50
  - coco_2way_cls46_51
  - coco_2way_cls46_52
  - coco_2way_cls46_53
  - coco_2way_cls46_54
  - coco_2way_cls46_55
  - coco_2way_cls46_56
  - coco_2way_cls46_57
  - coco_2way_cls46_58
  - coco_2way_cls46_59
  - coco_2way_cls47_48
  - coco_2way_cls47_49
  - coco_2way_cls47_50
  - coco_2way_cls47_51
  - coco_2way_cls47_52
  - coco_2way_cls47_53
  - coco_2way_cls47_54
  - coco_2way_cls47_55
  - coco_2way_cls47_56
  - coco_2way_cls47_57
  - coco_2way_cls47_58
  - coco_2way_cls47_59
  - coco_2way_cls48_49
  - coco_2way_cls48_50
  - coco_2way_cls48_51
  - coco_2way_cls48_52
  - coco_2way_cls48_53
  - coco_2way_cls48_54
  - coco_2way_cls48_55
  - coco_2way_cls48_56
  - coco_2way_cls48_57
  - coco_2way_cls48_58
  - coco_2way_cls48_59
  - coco_2way_cls49_50
  - coco_2way_cls49_51
  - coco_2way_cls49_53
  - coco_2way_cls49_54
  - coco_2way_cls49_55
  - coco_2way_cls49_56
  - coco_2way_cls49_57
  - coco_2way_cls49_58
  - coco_2way_cls49_59
  - coco_2way_cls50_51
  - coco_2way_cls50_52
  - coco_2way_cls50_53
  - coco_2way_cls50_54
  - coco_2way_cls50_55
  - coco_2way_cls50_56
  - coco_2way_cls50_57
  - coco_2way_cls50_58
  - coco_2way_cls50_59
  - coco_2way_cls51_52
  - coco_2way_cls51_53
  - coco_2way_cls51_55
  - coco_2way_cls51_56
  - coco_2way_cls51_57
  - coco_2way_cls51_58
  - coco_2way_cls51_59
  - coco_2way_cls52_53
  - coco_2way_cls52_54
  - coco_2way_cls52_55
  - coco_2way_cls52_56
  - coco_2way_cls52_57
  - coco_2way_cls52_58
  - coco_2way_cls52_59
  - coco_2way_cls53_54
  - coco_2way_cls53_55
  - coco_2way_cls53_56
  - coco_2way_cls53_57
  - coco_2way_cls53_58
  - coco_2way_cls53_59
  - coco_2way_cls54_55
  - coco_2way_cls54_56
  - coco_2way_cls54_57
  - coco_2way_cls54_58
  - coco_2way_cls54_59
  - coco_2way_cls55_56
  - coco_2way_cls55_57
  - coco_2way_cls55_58
  - coco_2way_cls55_59
  - coco_2way_cls56_57
  - coco_2way_cls56_58
  - coco_2way_cls56_59
  - coco_2way_cls57_58
  - coco_2way_cls57_59
  - coco_2way_cls58_59
  TRAIN:
  - coco14_base_sem_seg_fold2
  SAL_ROOT: ./datasets/COCO14/Sal_val
  VIS_MULTIPLIER: 127
GLOBAL:
  HACK: 1.0
INPUT:
  COLOR_AUG_SSD: true
  CROP:
    ENABLED: true
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE:
    - 640
    - 640
    TYPE: absolute
  DATASET_MAPPER_NAME: mask_former_semantic
  FORMAT: RGB
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 2560
  MAX_SIZE_TRAIN: 2560
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN:
  - 320
  - 384
  - 448
  - 512
  - 576
  - 640
  - 704
  - 768
  - 832
  - 896
  - 960
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
  SIZE_DIVISIBILITY: 640
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - -90
      - 0
      - 90
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES:
    - - 32
      - 64
      - 128
      - 256
      - 512
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_resnet_deeplab_backbone
  CLIP_ADAPTER:
    INSTANCE_WEIGHT: 0.01
    CLIP_ENSEMBLE: true
    CLIP_ENSEMBLE_WEIGHT: 0.7
    CLIP_MODEL_NAME: ViT-B/16
    MASK_EXPAND_RATIO: 1.0
    MASK_FILL: mean
    MASK_MATTING: false
    MASK_THR: 0.5
    PREDEFINED_PROMPT_TEMPLATES:
    - a sculpture of a {}.
    PROMPT_DIM: 512
    PROMPT_LEARNER: instance_learnable
    PROMPT_CHECKPOINT: ./output_coco/learn_instance/fold2/model_final.pth
    PROMPT_SHAPE:
    - 16
    - 0
    REGION_CLIP_ADAPTER:
      CLIP_MODEL_NAME: ViT-B/16
      PREDEFINED_PROMPT_TEMPLATES:
      - a sculpture of a {}.
      PROMPT_CHECKPOINT: ./output_coco/learn_instance/fold2/model_final.pth
      PROMPT_DIM: 512
      PROMPT_LEARNER: instance_learnable
      PROMPT_SHAPE:
      - 16
      - 0
    REGION_RESIZED: true
    SEPERATE_ADAPTER: false
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: []
    NORM: ''
    OUT_CHANNELS: 256
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_FORMER:
    DEC_LAYERS: 6
    DEEP_SUPERVISION: true
    DICE_WEIGHT: 1.0
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.1
    ENC_LAYERS: 0
    ENFORCE_INPUT_PROJ: false
    HIDDEN_DIM: 256
    MASK_WEIGHT: 20.0
    NHEADS: 8
    NO_OBJECT_WEIGHT: 0.1
    NUM_OBJECT_QUERIES: 100
    PRE_NORM: false
    SIZE_DIVISIBILITY: 32
    TEST:
      OBJECT_MASK_THRESHOLD: 0.0
      OVERLAP_THRESHOLD: 0.0
      PANOPTIC_ON: false
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: false
    TRANSFORMER_IN_FEATURE: res5
  MASK_ON: false
  META_ARCHITECTURE: ZeroShotMaskFormer
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: true
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.12
  - 57.375
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    RES2_OUT_CHANNELS: 256
    RES4_DILATION: 1
    RES5_DILATION: 1
    RES5_MULTI_GRID:
    - 1
    - 2
    - 4
    STEM_OUT_CHANNELS: 128
    STEM_TYPE: deeplab
    STRIDE_IN_1X1: false
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES:
    - p3
    - p4
    - p5
    - p6
    - p7
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.4
    - 0.5
    NMS_THRESH_TEST: 0.5
    NORM: ''
    NUM_CLASSES: 60
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS:
    - - 10.0
      - 10.0
      - 5.0
      - 5.0
    - - 20.0
      - 20.0
      - 10.0
      - 10.0
    - - 30.0
      - 30.0
      - 15.0
      - 15.0
    IOUS:
    - 0.5
    - 0.6
    - 0.7
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    BOUNDARY_THRESH: -1
    CONV_DIMS:
    - -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES:
    - res4
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.3
    - 0.7
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 12000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    ASPP_CHANNELS: 256
    ASPP_DILATIONS:
    - 6
    - 12
    - 18
    ASPP_DROPOUT: 0.1
    COMMON_STRIDE: 4
    CONVS_DIM: 256
    EMBEDDING_DIM: 512
    EMBED_HIDDEN_DIM: 1024
    EMBED_LAYERS: 2
    IGNORE_VALUE: 255
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    LOSS_TYPE: hard_pixel_mining
    LOSS_WEIGHT: 1.0
    MASK_DIM: 256
    NAME: ZeroShotMaskFormerHead
    NORM: GN
    NUM_CLASSES: 60
    PIXEL_DECODER_NAME: BasePixelDecoder
    PROJECT_CHANNELS:
    - 48
    PROJECT_FEATURES:
    - res2
    TRANSFORMER_ENC_LAYERS: 0
    USE_DEPTHWISE_SEPARABLE_CONV: false
  SWIN:
    APE: false
    ATTN_DROP_RATE: 0.0
    DEPTHS:
    - 2
    - 2
    - 6
    - 2
    DROP_PATH_RATE: 0.3
    DROP_RATE: 0.0
    EMBED_DIM: 96
    MLP_RATIO: 4.0
    NUM_HEADS:
    - 3
    - 6
    - 12
    - 24
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    PATCH_NORM: true
    PATCH_SIZE: 4
    PRETRAIN_IMG_SIZE: 224
    QKV_BIAS: true
    QK_SCALE: null
    WINDOW_SIZE: 7
  WEIGHTS: /home/iitd/prashant/WeakLSS/zsseg.baseline/output_coco/wzss/fold2/model_0004999.pth
ORACLE: false
OUTPUT_DIR: ./output_coco/wfss_2way/fold2
PSEUDO: false
PSEUDO_FLAG_NAME: trainable_flag
PSEUDO_REJECT_THRESHOLD: 0.0
PSEUDO_WITH_PRIOR: true
SEED: -1
SOLVER:
  AMP:
    ENABLED: false
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 0.01
    ENABLED: true
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 30
  LR_SCHEDULER_NAME: WarmupPolyLR
  MAX_ITER: 60000
  MOMENTUM: 0.9
  NESTEROV: false
  OPTIMIZER: ADAMW
  POLY_LR_CONSTANT_ENDING: 0.0
  POLY_LR_POWER: 0.9
  REFERENCE_WORLD_SIZE: 0
  STEPS:
  - 30000
  TEST_IMS_PER_BATCH: 1
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: null
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4480
    MIN_SIZES:
    - 320
    - 480
    - 640
    - 800
    - 960
    - 1120
  DENSE_CRF: false
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 20000
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
  SLIDING_OVERLAP: 0.6666666666666666
  SLIDING_TILE_SIZE: 224
  SLIDING_WINDOW: false
VERSION: 2
VIS_PERIOD: 0
WANDB:
  NAME: null
  PROJECT: zero_shot_seg
